name       : python-docker-pycreds
version    : 0.3.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/9e/7a/109e0a3cc3c19534edd843c16e792c67911b5b4072fdd34ddce90d49f355/docker-pycreds-0.3.0.tar.gz : 8b0e956c8d206f832b06aa93a710ba2c3bcbacb5a314449c040b0b814355bbff
license    : Apache-2.0
component  : programming.python
summary    : Python bindings for the docker credentials store API
description: |
    Python bindings for the docker credentials store API
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
