name       : python-docker-pycreds
version    : 0.4.0
release    : 8
source     :
    - git|https://github.com/shin-/dockerpy-creds.git : 0.4.0
license    : Apache-2.0
component  : programming.python
summary    : Python bindings for the docker credentials store API
description: |
    Python bindings for the docker credentials store API
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
